# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0

apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xmydatastores.ellin.net
spec:
  group: ellin.net
  connectionSecretKeys:
  - username
  - password
  - host
  - port
  - type
  names:
    kind: XMyDataStore
    plural: xmydatastores
  claimNames:
    kind: MyDataStore
    plural: mydatastores
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                mem:
                  type: integer