---
apiVersion: v1
kind: Service
metadata:
  name: spring-petclinic
  namespace: other-namespace
  annotations:
    kapp.k14s.io/change-group: workload
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: spring-petclinic

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-petclinic
  namespace: other-namespace
  annotations:
    kapp.k14s.io/change-group: workload
  labels:
    app: spring-petclinic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-petclinic
  template:
    metadata:
      annotations:
        kapp.k14s.io/deploy-logs: "for-new"
        kapp.k14s.io/deploy-logs-container-names: "workload"
      labels:
        app: spring-petclinic
    spec:
      containers:
        - name: workload
          # built with CNB Paketo builder from https://github.com/spring-projects/spring-petclinic
          image: registry.gcp.ellin.net/library/spring-petclinic:7
          env:
          # tell the workload to use mysql instead of the default embedded database
          - name: SPRING_PROFILES_ACTIVE
            value: postgres
          ports:
          - name: http
            containerPort: 8080
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: http
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: http
          startupProbe:
            httpGet:
              path: /actuator/health/liveness
              port: http
            failureThreshold: 20
            periodSeconds: 5