# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0

apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xmyhelmishdatastores.ellin.net
spec:
  group: ellin.net
  connectionSecretKeys:
  - username
  - password
  - host
  - port
  - type
  names:
    kind: XMyHelmishDataStore
    plural: xmyhelmishdatastores
  claimNames:
    kind: MyHelmishDataStore
    plural: myhelmishdatastores
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            status:
              type: object
              properties: 
                secondResource:
                  type: string
                binding:
                  type: object
                  properties:
                    name:
                      type: string
            spec:
              type: object
              properties:
                enablePersistence:
                  type: boolean